# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: BuildJob1
    steps:
    - script: echo Hello BuildJob1
  - job: BuildJob2
    steps:
    - script: echo Hello BuildJob2

- stage: DevDeploy
  jobs:
  - job: DevDeployJob
    steps:
    - script: echo Hello DevDeployJob 
- stage: QADeploy
  jobs:
  - job: QADeployJob
    steps:
    - script: echo Hello QADeployJob 
- stage: ProdDeploy
  jobs:
  - job: ProdDeployJob
    steps:
    - script: echo Hello ProdDeployJob 

